version: "3.8"

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - NAME=Docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres:/var/lib/postgresql/data